### ISSUE TITLE
ColorPicker: Uncaught TypeError: ctx2.value.toFormat is not a function

### ISSUE THREAD

**Issue by janhartmann** [chakra-ui/ark#2932]
### Description

Using the ColorPicker after updating to 4.0.0 crashes with:

```
chunk-SDLSYLIV.js?v=1cfdc11c:6554 Uncaught TypeError: ctx2.value.toFormat is not a function
    at areaValue (chunk-SDLSYLIV.js?v=1cfdc11c:6554:29)
    at desc.get (chunk-SDLSYLIV.js?v=1cfdc11c:477:22)
    at Reflect.get (<anonymous>)
    at chunk-SDLSYLIV.js?v=1cfdc11c:251:27
    at Array.forEach (<anonymous>)
    at createSnapshot (chunk-SDLSYLIV.js?v=1cfdc11c:250:27)
    at snapshot (chunk-SDLSYLIV.js?v=1cfdc11c:462:10)
    at new Machine (chunk-SDLSYLIV.js?v=1cfdc11c:1386:27)
    at createMachine (chunk-SDLSYLIV.js?v=1cfdc11c:1456:42)
    at machine (chunk-SDLSYLIV.js?v=1cfdc11c:6526:10)
```

<img width="493" alt="Screenshot 2024-09-29 at 10 40 54 AM" src="https://github.com/user-attachments/assets/aa4972f2-9cc4-472b-96ff-22e35c90cee9">

### Link to Reproduction (or Detailed Explanation)

N/A

### Steps to Reproduce

Unable to give example on this currently, but I have just added the color picker like this:

```ts
export const ColorPicker: React.FC<ColorPickerProps> = ({
  name,
  errorMessage,
  ...rest
}) => {
  return (
    <ArkColorPicker.Root {...rest}>
      <ArkColorPicker.Control>
        <ArkColorPicker.ChannelInput channel="hex" asChild={true}>
          <Input name={name} errorMessage={errorMessage}>
            <Trigger>
              <ValueSwatch />
            </Trigger>
          </Input>
        </ArkColorPicker.ChannelInput>
      </ArkColorPicker.Control>
      <ArkColorPicker.Positioner>
        <Content>
          <Area>
            <AreaBackground />
            <AreaThumb />
          </Area>
          <ControlGroup>
            <ArkColorPicker.EyeDropperTrigger asChild={true}>
              <Button icon={IconColorPicker} iconSize={16} />
            </ArkColorPicker.EyeDropperTrigger>
            <ControlSliders>
              <ChannelSlider channel="hue">
                <ChannelSliderTrack />
                <ChannelSliderThumb />
              </ChannelSlider>
              <ChannelSlider channel="alpha">
                <TransparencyGrid />
                <ChannelSliderTrack />
                <ChannelSliderThumb />
              </ChannelSlider>
            </ControlSliders>
          </ControlGroup>
          <View format="rgba">
            <ArkColorPicker.ChannelInput channel="hex" asChild={true}>
              <Input size="small" name={`${name}-hex`} />
            </ArkColorPicker.ChannelInput>
            <ArkColorPicker.ChannelInput channel="alpha" asChild={true}>
              <OpacityInput size="small" name={`${name}-alpha`} />
            </ArkColorPicker.ChannelInput>
          </View>
        </Content>
      </ArkColorPicker.Positioner>
      <ArkColorPicker.HiddenInput />
    </ArkColorPicker.Root>
  );
};``

### Ark UI Version

4.0.0

### Framework

- [X] React
- [ ] Solid
- [ ] Vue

### Browser

Google Chrome

### Additional Information

_No response_

**Comment by segunadebayo** [comment]
Please read the Changelog here
https://github.com/chakra-ui/ark/blob/main/packages/react/CHANGELOG.md#400---2024-09-25

You need to use the parseColor function when defining color values.
